sonar.projectKey=Perserverance-syn_Intelligent_E_Learning_Platform
sonar.projectName=SmartLearn AI API
sonar.organization=perserverance-syn
sonar.sources=backend
sonar.tests=backend/tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**,**/node_modules/**,frontend/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.qualitygate.wait=true
