sonar.projectKey=Perserverance-syn_Intelligent_E_Learning_Platform
sonar.projectName=SmartLearn AI API
sonar.organization=perserverance-syn
sonar.sources=backend
sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.pyc,**/migrations/**,**/node_modules/**,frontend/**
sonar.tests=backend/tests
sonar.language=python
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
